include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-sshproxy
PKG_VERSION:=1.1
PKG_RELEASE:=1
LUCI_TITLE:=LuCI SSH Proxy Injector (TLS)
LUCI_DEPENDS:=+luci-base +openssh-client +autossh +netcat-openbsd +openssl-util
LUCI_PKGARCH:=all
include $(TOPDIR)/feeds/luci/luci.mk
